### PR TITLE
Feat/add article ecmascript asynchronicity dynamic import

### PR DESCRIPTION
**Pull request by elfakamal**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
50 words might be misspelled, please check them: AMD, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, composée, config, de, d'un, ecmascript, élément, éléments, et, faire, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, l'affichage, les, lifecycle, liste, MessageEditor, minChunks, NodeJS, peut, polyfill, polyfills, qu'on, Rauschmayer's, RequireJS, Rollup, runtime, ses, StoryEditor, sur, SystemJS, transpiling, Une, visualisation, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
49 words might be misspelled, please check them: AMD, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, composée, config, de, d'un, élément, éléments, et, faire, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, l'affichage, les, lifecycle, liste, MessageEditor, minChunks, NodeJS, peut, polyfill, polyfills, qu'on, Rauschmayer's, RequireJS, Rollup, runtime, ses, StoryEditor, sur, SystemJS, transpiling, Une, visualisation, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, app’s, apreciate, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, app’s, apreciate, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
37 words might be misspelled, please check them: AMD, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
37 words might be misspelled, please check them: AMD, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, amongst, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenTom** [comment]
Il faut changer la date à aujourd'hui, puis je procède à la publication :) @elfakamal

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, amongst, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, amongst, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by ElevenWilson** [comment]
38 words might be misspelled, please check them: AMD, amongst, app’s, Asynchronicity, Axel, bundler, bundlers, CommonJS, CommonsChunkPlugin, componentDidMount, config, de, FormGroup, gzip, ing, Javascript's, js, jsx, kelfarsaoui, lifecycle, ListPage, MessageEditor, minChunks, NodeJS, polyfill, polyfills, Rauschmayer's, React's, RequireJS, Rollup, runtime, StoryEditor, StoryPage, SystemJS, transpiling, webpack, Webpack, Webpack's

**Comment by VEBERArnaud** [comment]
@ElevenTom, il faut supprimer la branche après le merge

**Pull request merged**
