### PR TITLE
feat(post): Moved vcomposieux's articles to markdown

### PR DESCRIPTION
**Pull request by eko**
All my following articles has been moved from `_drafts` to `_posts` using markdown.

I've also:
* Added my author page under `_authors/vcomposieux.md`,
* Added my author profile picture under `img/authors/vcomposieux.jpg`,
* Added the `Front Matter` to blog posts,
* Added the `permalink` to blog posts front matters.

List of blog posts updated:
- [X] Construct and structure a Go GraphQL API
- [X] Construire et structurer une API GraphQL en Go
- [X] Retours sur la dotScale 2017
- [X] HTTP/2 is not future. It's present.
- [X] HTTP/2 n'est pas le futur. C'est le présent.
- [X] Consul: Service Discovery and Failure Detection
- [X] Consul : Service Discovery et Failure Detection
- [X] Redux: Structure your frontend applications
- [X] Redux : Structurez vos applications front
- [X] Create your first Atom package
- [X] Créer votre premier package pour Atom
- [X] Use the Symfony Workflow component
- [X] Utiliser le composant Workflow de Symfony
- [X] Behat: structure your functional tests
- [X] Behat : structurez vos tests fonctionnels

### CODE REVIEW

**Comment by CaptainJojo** [comment]
si tu veux utilise ### pour tes titres le style est plus jolie :)

**Comment by eko** [comment]
I just added my last blog post about how to construct and structure a GraphQL API using Go :)

I think I will only have to add the i18n part when it will be added to the blog.

**Comment by CaptainJojo** [comment]
@eko un rebase sur master :)

**Comment by eko** [comment]
@CaptainJojo rebase done :)

**Pull request merged**
