### PR TITLE
OpenPGP - The almost perfect key pair

### PR DESCRIPTION
**Pull request by lepiaf**

### CODE REVIEW

**Comment by ElevenWilson** [comment]
19 words might be misspelled, please check them: addkey, AppData, conf, decrypting, gnupg, GnuPG, gpg, igning, io, keybase, openpgp, OpenPGP, PGP, RSA, subkey, subkeys, tthuon, username, Yubikey

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: addkey, AppData, cleé, decrypting, d'OpenPGP, évévenement, gnupg, GnuPG, gpg, io, keybase, l'identitié, openpgp, OpenPGP, PGP, regénérer, RSA, subkey, subkeys, tthuon, username, Yubikey

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: addkey, AppData, cleé, decrypting, d'OpenPGP, évévenement, gnupg, GnuPG, gpg, io, keybase, l'identitié, openpgp, OpenPGP, PGP, regénérer, RSA, subkey, subkeys, tthuon, username, Yubikey

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: addkey, AppData, cleé, decrypting, d'OpenPGP, évévenement, gnupg, GnuPG, gpg, io, keybase, l'identitié, openpgp, OpenPGP, PGP, regénérer, RSA, subkey, subkeys, tthuon, username, Yubikey

**Comment by ElevenTom** [comment]
Date à changer

**Comment by ElevenWilson** [comment]
22 words might be misspelled, please check them: addkey, AppData, cleé, decrypting, d'OpenPGP, évévenement, gnupg, GnuPG, gpg, io, keybase, l'identitié, openpgp, OpenPGP, PGP, regénérer, RSA, subkey, subkeys, tthuon, username, Yubikey

**Pull request merged**
